plugins {
    alias libs.plugins.androidLibrary
    alias libs.plugins.kotlinAndroid
}

group = 'io.github.seker'
version = '1.0.2-SNAPSHOT'

android {
    namespace 'seker.asynctask.android'

    compileSdkVersion libs.versions.android.compileSdk.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.android.minSdk.get().toInteger()
        targetSdkVersion libs.versions.android.targetSdk.get().toInteger()

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        consumerProguardFiles "consumer-rules.pro"
    }

    sourceSets {
        main.java.srcDirs = ['src/main/java', '../asynctask/src/main/java']
        test.java.srcDirs = ['src/test/java', '../asynctask/src/test/java']
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
    }
}

dependencies {
//    implementation project(":asynctask")

    testImplementation libs.junit
    androidTestImplementation libs.androidx.testExt.junit
    androidTestImplementation libs.androidx.espresso.core

//    testImplementation libs.junit.jupiter.api
//    testRuntimeOnly libs.junit.jupiter.engine
}

apply from: 'publish.gradle'