plugins {
    id 'java'
}
apply from: 'publish.gradle'

dependencies {
    testImplementation libs.junit

//    testImplementation libs.junit.jupiter.api
//    testRuntimeOnly libs.junit.jupiter.engine
}

test {
    useJUnitPlatform()
}

java {
    sourceCompatibility JavaVersion.VERSION_21
    targetCompatibility JavaVersion.VERSION_21
}
